#!/usr/bin/env python
''' This script requires a SQLite database, which can be generated by the 
EcoData Retriever:

retriever install sqlite [dataset] -f [dataset].sqlite
''' 
import sqlite3 as dbapi
import csv
import sys
dataset = sys.argv[1]

con = dbapi.connect('data/%s.sqlite' % dataset)
query = open('data/%s_query.sql' % dataset).read()
cur = con.cursor()
cur.execute(query)

with sys.stdout as output_file:
    writer = csv.writer(output_file)
    writer.writerow(('route', 'lat','lon','genus','species','count'))
    for row in cur:
        try:
            lat = round(float(row[1]), 3)
            lon = round(float(row[2]), 3)
            writer.writerow(row)
        except TypeError: continue
